//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string NameAdminUser { get; set; }
        public string Gender { get; set; }
        public string Image { get; set; }
        public string Role { get; set; }
    }
}
