//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailForm()
        {
            this.DiseaseStatistics = new HashSet<DiseaseStatistic>();
        }
    
        public int DFId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalMoney { get; set; }
        public bool IsExamined { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> FOId { get; set; }
        public Nullable<int> PriceListId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual FormOnline FormOnline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiseaseStatistic> DiseaseStatistics { get; set; }
    }
}
