//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseStatistic
    {
        public int DSLId { get; set; }
        public string Diagnose { get; set; }
        public Nullable<int> DFId { get; set; }
    
        public virtual DetailForm DetailForm { get; set; }
    }
}
