//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseStatisticList
    {
        public int IdDSL { get; set; }
        public string Dianose { get; set; }
        public int IdForm { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
